name: betamax
description: >
  Record your test suite's HTTP interactions and replay them during future test
  runs for fast, deterministic, accurate tests.
version: 1.0.0-dev.1
repository: https://github.com/madewithfelt/betamax

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  meta: ^1.0.0
  nock: ^1.2.0
  path: ^1.0.0
  pedantic: ^1.11.0
  slugify_string: ^2.0.0
  test_api: ^0.2.0
  test: ^1.16.5
