name: betamax
description: >
  Record your test suite's HTTP interactions and replay them during future test
  runs for fast, deterministic, accurate tests.

  Like Ruby's VCR gem!
version: 1.0.7
repository: https://github.com/shyndman/betamax

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  http: ^0.13.0
  meta: ^1.0.0
  nock: ^1.2.0
  path: ^1.0.0
  lints: ^1.0.1
  slugify_string: ^2.0.0
  stack_trace: ^1.0.0
  test_api: ^0.4.0
  test: ^1.18.0
