name: http_recorder
description: An http compatible client capable of performing
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.13.0

dev_dependencies:
  build_runner: ^1.0.0
  built_value: ^8.0.0
  json_serializable: ^3.0.0
  pedantic: ^1.11.0
  test: ^1.16.5
